inherit_from:
#  - C:/Tools/Ruby/.gem/gems/rubocop-0.44.1/config/default.yml
#  - C:/Tools/Ruby/Ruby-2.2.5-32/.gem/gems/rubocop-0.44.1/config/default.yml
  - C:/Tools/Ruby/Ruby-2.3.1-32/.gem/gems/rubocop-0.44.1/config/default.yml
  
AllCops:
  Exclude:
  - src/test/**/*
  
require: rubocop-rspec 
